require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  SuggestExtensions: false
  Exclude: 
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'config/**/*'
    - 'app/mailers/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'let']

Style/ClassAndModuleChildren:
    Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false