default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres
  password: postgres

development:
  <<: *default
  database: eco_loop_development

test:
  <<: *default
  database: eco_loop_test

